version: "3"

services:
    lms_pma:
        image: phpmyadmin/phpmyadmin
        container_name: lms_pmass
        restart: unless-stopped
        environment:
            PMA_HOST: library-db.cdsw4o4qoqsj.eu-north-1.rds.amazonaws.com
            PMA_PORT: 3306
            PMA_USERNAME: admin
            PMA_PASSWORD: Shreyas2222
            # PMA_ARBITRARY: 1
        ports:
            - 8081:80
volumes:
    dbdata:
